import Foundation

/// One published release in the appcast Sparkle polls.
public struct AppcastItem: Equatable {
    public var version: AppVersion
    public var title: String
    public var link: String
    public var pubDate: String
    public var enclosureURL: String
    public var enclosureLength: Int
    /// Sparkle's `sparkle:edSignature` -- the EdDSA signature over the exact
    /// bytes of the download, produced by Sparkle's own `sign_update` tool
    /// with the private key that lives only in Brady's Keychain. Sparkle
    /// refuses any update whose signature does not verify against the
    /// `SUPublicEDKey` baked into the installed app, so this is the field
    /// that makes the whole feed safe to serve over a static host.
    public var edSignature: String
    public var minimumSystemVersion: String

    public init(
        version: AppVersion,
        title: String,
        link: String,
        pubDate: String,
        enclosureURL: String,
        enclosureLength: Int,
        edSignature: String,
        minimumSystemVersion: String
    ) {
        self.version = version
        self.title = title
        self.link = link
        self.pubDate = pubDate
        self.enclosureURL = enclosureURL
        self.enclosureLength = enclosureLength
        self.edSignature = edSignature
        self.minimumSystemVersion = minimumSystemVersion
    }
}

/// Read/modify/write for the appcast feed served at
/// https://bradystroud.github.io/browser/appcast.xml (the file lives in
/// `docs/`, which GitHub Pages already publishes for the landing page --
/// browser-wc7).
///
/// Deliberately a full parse-and-re-render rather than a textual splice into
/// the existing file. This repo is the only writer of that file, the schema
/// is fixed and small, and re-rendering from a parsed model means a release
/// can never append a second `<item>` for a version already in the feed, or
/// leave the items out of order -- both of which a `sed`-shaped approach
/// gets wrong the first time someone re-cuts a release.
public enum AppcastDocument {
    public static let channelTitle = "Browser"
    public static let channelDescription = "Updates for Browser, a native macOS browser."
    public static let channelLink = "https://bradystroud.github.io/browser/appcast.xml"

    // MARK: - Parsing

    public enum ParseError: Error, CustomStringConvertible {
        case malformedXML(String)
        case itemMissingField(String)

        public var description: String {
            switch self {
            case .malformedXML(let detail): return "appcast is not well-formed XML: \(detail)"
            case .itemMissingField(let field): return "appcast <item> is missing \(field)"
            }
        }
    }

    /// Parses an appcast's items. Channel-level metadata is not read back --
    /// `render(items:)` always writes the constants above, so the channel
    /// header cannot drift release to release.
    public static func parseItems(xml: String) throws -> [AppcastItem] {
        let delegate = ItemParserDelegate()
        let parser = XMLParser(data: Data(xml.utf8))
        parser.delegate = delegate
        guard parser.parse() else {
            throw ParseError.malformedXML(parser.parserError?.localizedDescription ?? "unknown error")
        }
        if let missing = delegate.missingField {
            throw ParseError.itemMissingField(missing)
        }
        return delegate.items
    }

    // MARK: - Merging

    /// Returns `items` with `newItem` added, or replacing the existing entry
    /// for the same version, sorted newest-first.
    ///
    /// Replace-rather-than-append is the point: re-cutting a release (a
    /// failed notarization, a re-uploaded DMG) changes the download's length
    /// and signature, and an appended duplicate would leave Sparkle picking
    /// between two `<item>`s claiming the same version with different
    /// signatures.
    public static func upsert(_ newItem: AppcastItem, into items: [AppcastItem]) -> [AppcastItem] {
        var merged = items.filter { $0.version != newItem.version }
        merged.append(newItem)
        return merged.sorted { $0.version > $1.version }
    }

    // MARK: - Rendering

    public static func render(items: [AppcastItem]) -> String {
        var xml = """
        <?xml version="1.0" encoding="utf-8"?>
        <!-- Generated by Packages/UpdateCore's appcast-tool, from
             scripts/release.sh. Edit that, not this. -->
        <rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle">
          <channel>
            <title>\(escape(channelTitle))</title>
            <link>\(escape(channelLink))</link>
            <description>\(escape(channelDescription))</description>
            <language>en</language>

        """

        for item in items.sorted(by: { $0.version > $1.version }) {
            xml += """
                <item>
                  <title>\(escape(item.title))</title>
                  <link>\(escape(item.link))</link>
                  <sparkle:version>\(escape(item.version.description))</sparkle:version>
                  <sparkle:shortVersionString>\(escape(item.version.description))</sparkle:shortVersionString>
                  <sparkle:releaseNotesLink>\(escape(item.link))</sparkle:releaseNotesLink>
                  <sparkle:minimumSystemVersion>\(escape(item.minimumSystemVersion))</sparkle:minimumSystemVersion>
                  <pubDate>\(escape(item.pubDate))</pubDate>
                  <enclosure url="\(escape(item.enclosureURL))" sparkle:edSignature="\(escape(item.edSignature))" length="\(item.enclosureLength)" type="application/octet-stream"/>
                </item>

            """
        }

        xml += """
          </channel>
        </rss>

        """
        return xml
    }

    private static func escape(_ value: String) -> String {
        value
            .replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
    }

    /// RFC 822 date, the format RSS (and therefore Sparkle) expects. Forced
    /// to the POSIX locale so a release cut on a machine set to another
    /// language does not emit month names no RSS reader can parse.
    public static func rfc822(_ date: Date, timeZone: TimeZone = .current) -> String {
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = timeZone
        formatter.dateFormat = "EEE, dd MMM yyyy HH:mm:ss Z"
        return formatter.string(from: date)
    }
}

/// XMLParser is push-based, so accumulating items needs a delegate object
/// rather than a closure -- kept file-private to `AppcastDocument`'s API.
private final class ItemParserDelegate: NSObject, XMLParserDelegate {
    var items: [AppcastItem] = []
    var missingField: String?

    private var inItem = false
    private var currentElement = ""
    private var text = ""
    private var fields: [String: String] = [:]
    private var enclosure: [String: String] = [:]

    func parser(
        _ parser: XMLParser,
        didStartElement elementName: String,
        namespaceURI: String?,
        qualifiedName qName: String?,
        attributes attributeDict: [String: String] = [:]
    ) {
        // qName carries the "sparkle:" prefix; elementName does not, and
        // <version>/<sparkle:version> must not be conflated.
        let name = qName ?? elementName
        if name == "item" {
            inItem = true
            fields = [:]
            enclosure = [:]
            return
        }
        if inItem && name == "enclosure" {
            enclosure = attributeDict
        }
        currentElement = name
        text = ""
    }

    func parser(_ parser: XMLParser, foundCharacters string: String) {
        text += string
    }

    func parser(
        _ parser: XMLParser,
        didEndElement elementName: String,
        namespaceURI: String?,
        qualifiedName qName: String?
    ) {
        let name = qName ?? elementName
        guard inItem else { return }

        if name == "item" {
            inItem = false
            appendItem()
            return
        }
        if name == currentElement {
            fields[name] = text.trimmingCharacters(in: .whitespacesAndNewlines)
        }
    }

    private func appendItem() {
        guard missingField == nil else { return }

        func require(_ value: String?, _ label: String) -> String? {
            guard let value, !value.isEmpty else {
                missingField = label
                return nil
            }
            return value
        }

        guard let rawVersion = require(fields["sparkle:version"], "<sparkle:version>"),
              let version = AppVersion(rawVersion) else {
            missingField = missingField ?? "a parsable <sparkle:version>"
            return
        }
        guard let url = require(enclosure["url"], "an <enclosure url>"),
              let signature = require(enclosure["sparkle:edSignature"], "an <enclosure sparkle:edSignature>"),
              let rawLength = require(enclosure["length"], "an <enclosure length>"),
              let length = Int(rawLength) else {
            missingField = missingField ?? "a numeric <enclosure length>"
            return
        }

        items.append(AppcastItem(
            version: version,
            title: fields["title"] ?? version.description,
            link: fields["link"] ?? "",
            pubDate: fields["pubDate"] ?? "",
            enclosureURL: url,
            enclosureLength: length,
            edSignature: signature,
            minimumSystemVersion: fields["sparkle:minimumSystemVersion"] ?? ""
        ))
    }
}
